config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'
  devise_for :admins , controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'registrations'
  }
  resources :admins, only:[:index, :destroy]

  delete 'admins/destroy' => 'admins#destroy'

  get 'abouts/index'

  root 'cars#index'

  devise_for :users, :controllers => {:registrayions => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :cars do
    resource :comments, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :events, only:[:index, :new, :create, :edit, :update, :destroy]



  post 'cars/create' => 'cars#create'

  post 'car_years/create' => 'car_years#create'
  post 'car_years/update' => 'car_years#update'

  post 'car_models/create' => 'car_models#create'
  post 'car_models/update' => 'car_models#update'

  post 'manufactures/create' => 'manufactures#create'
  post 'manufactures/destroy' => 'manufactures#destroy'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

    has_many :cars, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:show]


  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	if user.update(user_params)
  		sign_in(user, bypass: true)
  		redirect_to user_path(user.id)
  	else
  		redirect_to edit_user_path(user.id)
  	end
  end

  def destroy
    current_user.destroy
    flash[:notice] = "退会手続き完了しました。またのご利用お待ちしております。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :area, :email,:password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="user-edit-page" style="margin: 40px; text-align: center;">
  <h2>会員情報編集</h2>


  <%= form_for(@user) do |f| %>


    <div class="field">
      <h5>ニックネーム</h5>
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <h5>エリア</h5>
      <%= f.text_field :area, autofocus: true, autocomplete: "area" %>
    </div>


    <div class="field">
      <%= f.label :Eメール %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :パスワード %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> 文字以上)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :パスワード（確認） %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions" style="margin-top: 10px;">
      <%= f.submit "編集する", :class => "btn btn-info"%>
      <%= link_to "退会する", user_registration_path, method: :delete, "data-confirm" => "本当に退会しますか？",:class => "btn btn-danger"%>
    </div>

  <% end %>

</div>

app/views/users/show.html.erb
<div class="car-show container">
	<div class="row" style="text-align: center;">

		<% if flash[:notice] %>
      		<div class="container">
        		<div class="row">
          			<div class="alert alert-success" role="alert">
            			<div class="flash">
              				<%= flash[:notice] %>
            			</div>
          			</div>
        		</div>
      		</div>
    	 <% end %>

		<h2 style="margin-top: 40px;"><%= @user.name %>さんの部屋</h2>
		<h3><%= @user.area %></h3>

		<div class="user-cars clearfix">
			<% @user.cars.each do |uc| %>
				<%= link_to car_path(uc.id) do %>
					<div class="user-car" style="float: right; position: relative; left: -50%; text-align: left;">
						<ul class="list-group col-sm-3" style="width: 100%; text-align: center; position: relative; left: 50%;">
							<li class="list-group-item"><%= attachment_image_tag uc, :image, class: "profile-thumb", size: "540x400" %></li>
							<li class="list-group-item" style="color: black;"><%= uc.car_year.car_year %> <%= uc.manufacture.manufacture %> <%= uc.car_model.car_model %></li>
							<% if user_signed_in? && @user.id == current_user.id %>
								<li><button class="btn btn-info" style="margin-top: 10px;"><%= link_to "愛車を編集", edit_car_path(uc.id), :style=>"color: white;"%></button></li>
							<% end %>
						</ul>
					</div>
				<% end %>
			<% end %>
		</div>


		<% if user_signed_in? && @user.id == current_user.id or admin_signed_in?%>
			<div class="user-links" style="margin: 40px 0">
				<%= link_to "情報編集", edit_user_path, :class=>"btn btn-info" %>
				<%= link_to "愛車追加", new_car_path, :class=>"btn btn-info" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>