config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'
  devise_for :admins , controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'registrations'
  }
  resources :admins, only:[:index, :destroy]

  delete 'admins/destroy' => 'admins#destroy'

  get 'abouts/index'

  root 'cars#index'

  devise_for :users, :controllers => {:registrayions => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :cars do
    resource :comments, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :events, only:[:index, :new, :create, :edit, :update, :destroy]



  post 'cars/create' => 'cars#create'

  post 'car_years/create' => 'car_years#create'
  post 'car_years/update' => 'car_years#update'

  post 'car_models/create' => 'car_models#create'
  post 'car_models/update' => 'car_models#update'

  post 'manufactures/create' => 'manufactures#create'
  post 'manufactures/destroy' => 'manufactures#destroy'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	validates :introduction, presence: true
	validates :image, presence: true
	validates :manufacture_id, :numericality => { :greater_than => 2 }
	validates :car_model_id, :numericality => { :greater_than => 2 }

	belongs_to :user
	belongs_to :manufacture
	belongs_to :car_model
	belongs_to :car_year

	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	def  favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	attachment :image
end

app/models/car_model.rb
class CarModel < ApplicationRecord
	has_many :cars
end

app/models/car_year.rb
class CarYear < ApplicationRecord
	has_many :cars
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :car
end

app/models/event.rb
class Event < ApplicationRecord
	validates :event_date, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :car
end

app/models/manufacture.rb
class Manufacture < ApplicationRecord
	has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

    has_many :cars, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @search = Car.ransack(params[:q])
    @cars = @search.result(distinct: true).order('created_at DESC')
    @manufactures = Manufacture.all
    @car_models = CarModel.all
    @car_years = CarYear.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    if @car.save
      flash[:notice] = "愛車を登録しました。"
      redirect_to @car
    else
      flash[:notice] = "愛車を登録できません。"
      render 'new'
    end
  end

  def show
    @car = Car.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    flash[:notice] = "愛車を削除しました。"
    redirect_to user_path(current_user.id)
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    car = Car.find(params[:id])
    car.update(car_params)
    redirect_to car_path(car.id)

  end

  def set_search

  end

  private

    def car_params
      params.require(:car).permit(:manufacture_id, :car_model_id, :car_year_id, :image, :introduction)
    end

  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_admin!, except: [:index]


  def index
  	@events = Event.all.order(event_date: "ASC")
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
  	@event.save
  	flash[:notice] = "新しいイベントを追加しました。"
  	redirect_to events_path
  end

  def destroy
  	@event = Event.find(params[:id])
  	@event.destroy
  	flash[:notice] = "イベントを削除しました。"
  	redirect_to events_path
  end

  def edit
  	@event = Event.find(params[:id])
  end

  def update
  	@event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_path
  end


private

	def event_params
		params.require(:event).permit(:event_name, :event_address, :event_date)
	end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_years_helper.rb
module CarYearsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/manufactures_helper.rb
module ManufacturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="container new-car" style="margin: 60px auto; text-align: center;">
	<div class="row">
		<h2>イベントを編集</h2>

		<%= form_for(@event) do |f| %>


			<div class="field">
		      <%= f.label :イベント名 %><br />
		      <%= f.text_area :event_name %>
		    </div>

		    <div class="field">
		      <%= f.label :場所 %><br />
		      <%= f.text_area :event_address %>
		    </div>

		    <div class="field">
		      <%= f.label :日付 %><br />
		      <%= f.date_select :event_date %>
		    </div>

		    <div class="field" style="margin-top: 10px;">
		    	<%= f.submit "編集", :class => "btn btn-info"%>
		    	<%= link_to "削除", event_path(@event), method: :delete, :class => "btn btn-danger"%>
		    </div>


		<% end %>
	</div>
</div>

app/views/events/index.html.erb
<div class="event container">
	<div class="row">

		<h3 style="padding: 10px 0 ; text-align: center;">イベント一覧</h3>
		<table class="table col-md-12 col-xs-12">
			<thead>
				<tr>
					<th>イベント名</th>
					<th>場所</th>
					<th>日付</th>
					<% if admin_signed_in? %>
						<th>編集</th>
					<% end %>
					</if>
				</tr>
			</thead>
			<tbody>
				<% @events.each do |event| %>
					<tr>
						<td><%= event.event_name %></td>
						<td><%= event.event_address %></td>
						<td><%= event.event_date%></td>
						<% if admin_signed_in? %>
							<td><%= link_to "編集", edit_event_path(event),:class => "btn btn-info"%></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>

app/views/events/new.html.erb
<div class="container new-car" style="margin: 60px auto; text-align: center;">
	<div class="row">
		<h2>イベントを追加</h2>

		<%= form_for(@event, url:events_path) do |f| %>


			<div class="field">
		      <%= f.label :イベント名 %><br />
		      <%= f.text_area :event_name %>
		    </div>

		    <div class="field">
		      <%= f.label :場所 %><br />
		      <%= f.text_area :event_address %>
		    </div>

		    <div class="field">
		      <%= f.label :日付 %><br />
		      <%= f.date_select :event_date %>
		    </div>

		    <div class="field" style="margin-top: 10px;">
		    	<%= f.submit "登録", :class => "btn btn-info"%>
		    </div>


		<% end %>
	</div>
</div>