config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'
  devise_for :admins , controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'registrations'
  }
  resources :admins, only:[:index, :destroy]

  delete 'admins/destroy' => 'admins#destroy'

  get 'abouts/index'

  root 'cars#index'

  devise_for :users, :controllers => {:registrayions => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :cars do
    resource :comments, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :events, only:[:index, :new, :create, :edit, :update, :destroy]



  post 'cars/create' => 'cars#create'

  post 'car_years/create' => 'car_years#create'
  post 'car_years/update' => 'car_years#update'

  post 'car_models/create' => 'car_models#create'
  post 'car_models/update' => 'car_models#update'

  post 'manufactures/create' => 'manufactures#create'
  post 'manufactures/destroy' => 'manufactures#destroy'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	validates :introduction, presence: true
	validates :image, presence: true
	validates :manufacture_id, :numericality => { :greater_than => 2 }
	validates :car_model_id, :numericality => { :greater_than => 2 }

	belongs_to :user
	belongs_to :manufacture
	belongs_to :car_model
	belongs_to :car_year

	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	def  favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	attachment :image
end

app/models/car_model.rb
class CarModel < ApplicationRecord
	has_many :cars
end

app/models/car_year.rb
class CarYear < ApplicationRecord
	has_many :cars
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :car
end

app/models/event.rb
class Event < ApplicationRecord
	validates :event_date, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :car
end

app/models/manufacture.rb
class Manufacture < ApplicationRecord
	has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

    has_many :cars, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @search = Car.ransack(params[:q])
    @cars = @search.result(distinct: true).order('created_at DESC')
    @manufactures = Manufacture.all
    @car_models = CarModel.all
    @car_years = CarYear.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    if @car.save
      flash[:notice] = "愛車を登録しました。"
      redirect_to @car
    else
      flash[:notice] = "愛車を登録できません。"
      render 'new'
    end
  end

  def show
    @car = Car.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    flash[:notice] = "愛車を削除しました。"
    redirect_to user_path(current_user.id)
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    car = Car.find(params[:id])
    car.update(car_params)
    redirect_to car_path(car.id)

  end

  def set_search

  end

  private

    def car_params
      params.require(:car).permit(:manufacture_id, :car_model_id, :car_year_id, :image, :introduction)
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:show]


  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	if user.update(user_params)
  		sign_in(user, bypass: true)
  		redirect_to user_path(user.id)
  	else
  		redirect_to edit_user_path(user.id)
  	end
  end

  def destroy
    current_user.destroy
    flash[:notice] = "退会手続き完了しました。またのご利用お待ちしております。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :area, :email,:password, :password_confirmation)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_years_helper.rb
module CarYearsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/manufactures_helper.rb
module ManufacturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<div class="container new-car" style="margin: 60px auto; text-align: center;">
	<div class="row">
		<h2>愛車を編集</h2>

		<%= form_for(@car, url: car_path) do |f| %>


			<div class="field">
		      <%= f.label :メーカー %><br />
		      <%= f.collection_select :manufacture_id, Manufacture.all, :id, :manufacture %>
		    </div>

		    <div class="field">
		      <%= f.label :車種 %><br />
		      <%= f.collection_select :car_model_id, CarModel.all, :id, :car_model %>
		    </div>

		    <div class="field">
		      <%= f.label :年式 %><br />
		      <%= f.collection_select :car_year_id, CarYear.all, :id, :car_year %>
		    </div>

		    <div class="field">
		      <%= f.label :画像 %><br />
		      <%= f.attachment_field :image,:style => "margin: 0 auto; color: white;"%>
		    </div>

		    <div class="field">
		      <%= f.label :紹介文 %><br />
		      <%= f.text_area :introduction, :style => "height: 240px; width: 460px;"%>
		    </div>

		    <div class="field" style="margin-top: 10px;">
		    	<%= f.submit "愛車を編集", :class => "btn btn-info"%>
		    	<%= link_to "愛車を削除", car_path(@car), method: :delete, :class => "btn btn-danger"%>
		    </div>


		<% end %>
	</div>
</div>

app/views/cars/index.html.erb
<div class="container" style="width: 100%;">
	<div class="row">

		<div class="main-visual" style="background-image:url(<%= asset_path "/images/index.JPG" %>)">
			<div class="search-box" style="text-align: center; height: 500px;">

				<% if flash[:notice] %>
      				<div class="container">
        				<div class="row">
          					<div class="alert alert-success" role="alert">
            					<div class="flash">
              						<%= flash[:notice] %>
            					</div>
          					</div>
        				</div>
      				</div>
     			<% end %>

				<h2 style="margin: 0; padding: 20px 0;">VIPカー愛好家の集い</h2>
	            <%= search_form_for @search do |f| %>
	            	<div class="search-form">
	            		<%= f.label :フリーワード検索 %><br />
	                	<%= f.text_field :introduction_cont, placeholder: ' AIMGAINエアロ,シャコタンなど...', :size => "40*40"%>
	                </div>
	                <div class="search-form">
	                	<%= f.label :メーカー検索 %><br />
	                	<%= f.collection_select :manufacture_id_eq, @manufactures, :id, :manufacture, :include_blank => '指定なし'%>
	                </div>
	                <div class="search-form">
	                	<%= f.label :車種検索 %><br />
	                	<%= f.collection_select :car_model_id_eq, @car_models, :id, :car_model, :include_blank => '指定なし'%>
	                </div>
	                <div class="search-form">
	                	<%= f.label :年式検索 %><br />
	                	<%= f.collection_select :car_year_id_eq, @car_years, :id, :car_year, :include_blank => '指定なし'%>
	                </div>
	                <div class="action" style="margin-top: 10px;">
	                    <%= f.submit "検索", :class => "btn btn-info" %>
	                </div>
	            <% end %>
	        </div>
	     </div>

	     <div class="car-index-title" style="margin: 20px 0; text-align: center;">
	     	<h4>登録車両</h4>
	     </div>

	    <div class="container cars-index" style="width: 100% margin: 0 40px;">
	    	<div class="row">
				<% @cars.each do |car| %>
					<%= link_to car_path(car.id) do %>
						<ul class="list-group col-sm-6 center-block" style="width: 50%; color: black; text-align: center;">
							<li class="list-group-item"><%= attachment_image_tag car, :image, class: "profile-thumb", size: "540x400" %></li>
							<li class="list-group-item"><%= car.car_year.car_year %> <%= car.manufacture.manufacture %> <%= car.car_model.car_model %></li>
							<li class="list-group-item"><%= car.user.name %></li>
							<li class="list-group-item"><%= car.user.area %></li>
						</ul>
					<% end %>
				<% end %>
			</div>
		</div>

	</div>
</div>

app/views/cars/new.html.erb
<div class="container new-car" style="margin: 60px auto; text-align: center;">
	<div class="row">
		<h2>愛車を追加</h2>

		<%= form_for(@car, url:cars_path) do |f| %>


			<div class="field">
		      <%= f.label :メーカー %><br />
		      <%= f.collection_select :manufacture_id, Manufacture.all, :id, :manufacture %>
		    </div>

		    <div class="field">
		      <%= f.label :車種 %><br />
		      <%= f.collection_select :car_model_id, CarModel.all, :id, :car_model %>
		    </div>

		    <div class="field">
		      <%= f.label :年式 %><br />
		      <%= f.collection_select :car_year_id, CarYear.all, :id, :car_year %>
		    </div>

		    <div class="field">
		      <%= f.label :画像 %><br />
		      <%= f.attachment_field :image,:style => "margin: 0 auto; color: white;"%>
		    </div>

		    <div class="field">
		      <%= f.label :紹介文 %><br />
		      <%= f.text_area :introduction, :style => "height: 240px; width: 460px;"%>
		    </div>

		    <div class="field" style="margin-top: 10px;">
		    	<%= f.submit "愛車を登録", :class => "btn btn-info"%>
		    </div>


		<% end %>
	</div>
</div>

app/views/cars/show.html.erb
<div class="container" style="margin: 40px auto;">
	<div class="row">
		<div class="col-sm-12">
			<div class="car-image">
				<%= attachment_image_tag @car, :image, :fill, 700, 550, format: 'jpeg', :class => "img-responsive good.photo", :style => "margin: 0 auto;" %>
			</div>
			<div class="col-sm-12">
				<div class="car-info" style="text-align: center;">
					<h3><%= @car.car_year.car_year %> <%= @car.manufacture.manufacture %> <%= @car.car_model.car_model %></h3>
					<%= link_to user_path(@car.user.id),:style=>"color: white;" do %>
						<h4><%= @car.user.name %></h4>
					<% end %>
					<h4><%= @car.user.area %></h4>
				</div>
				<div class="car-text">
					<p><%= simple_format(@car.introduction)%></p>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="favorite container" style="margin-bottom: 10px;">
	<div class="row">
		<div class="col-sm-6">

			<% if user_signed_in? && @car.favorited_by?(current_user) %>
				<%= link_to car_favorites_path(@car), :style=>"color: white;", method: :delete do %>
			      <div class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></div>
			      <%= @car.favorites.count %> いいね
			    <% end %>
			<% elsif user_signed_in? %>
			    <%= link_to car_favorites_path(@car), :style=>"color: white;", method: :post do %>
			      <div class="glyphicon glyphicon-heart" aria-hidden="true" style="color: white;"></div>
			      <%= @car.favorites.count %> いいね
			    <% end %>
			<% else %>
				<div class="glyphicon glyphicon-heart" aria-hidden="true" style="color: white;"></div>
			      <%= @car.favorites.count %> いいね
			<% end %>
		</div>
	</div>
</div>

<% if user_signed_in? %>
	<div class="container comment-form" style="text-align: center;">
		<%= form_for [@car, @comment] do |f| %>
		    <div class="row">
		    	<div class="form-group">
				<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
				<%= f.submit "コメントする", :class => "btn btn-info", :style => "margin: 20px auto;" %>
				</div>
		    </div>
		<% end %>
	</div>
<% end %>


<div class="comments" style=" margin-bottom: 20px;">
	<% @car.comments.each do |car_comment| %>
		<div class="container">
		    <div class="row">
		        <div class="col-md-8">
		            <div class="comments-list" style="margin: 10px 0;">
		                <div class="media">
		                    <p class="pull-right"><small><%= car_comment.created_at.strftime('%Y/%m/%d') %></small></p>
		                        <div class="media-body">
		                        	<%= link_to user_path(car_comment.user.id), :style=>"color: white;" do %>
		                            	<h5 class="media-heading user_name"><%= car_comment.user.name %></h5>
		                            <% end %>
		                            <p><%= car_comment.comment %></p>
		                            	<% if car_comment.user == current_user %>
		                            		<button class="btn btn-danger" style="padding: 0px 10px;"><small><%= link_to "削除", car_comments_path(id: car_comment, car_id: @car), method: :delete, "data-confirm" => "本当にこのコメントを削除しますか？", :style=>"color: white;" %></small></button>
		                            	<% end %>
		                        </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	<% end %>
</div>